#!/usr/bin/env bash
# This script should kill process 4

PID=$(pgrep -f "4-to_infinity_and_beyond")

if [ -n "$PID" ]; then
    kill "$PID"
    echo "Terminated"
else
    echo "Process is not running"
fi
