#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

i=10
count=0

while [ $count -lt $i ];do

        echo "Best School"
	
	if [ $count -eq 8 ]
	then
		echo "hi"
	fi

        ((count++))
done
