#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

i=10
count=0

while [ $count -lt $i ];do

        echo "Best School"

        if [ $count -eq 3 ]
        then
                echo "back luck"
	elif [ $count -eq 7 ]
		echo "good luck"
	else
		echo "Best School"
        fi

        ((count++))
done
