#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and displays a message for specific iterations

count=1

while [ $count -le 20 ]; do
    case $count in
        4)
            echo "$count - Bad luck from China"
            ;;
        9)
            echo "$count - Bad luck from Japan"
            ;;
        17)
            echo "$count - Bad luck from Italy"
            ;;
        *)
            echo "$count"
            ;;
    esac

    ((count++)) # Increment the counter
done
