#!/usr/bin/env bash
# This script displays the content of the current directory

for file in *; do
    if [ -f "$file" ] && [[ "$file" != .* ]]; then
        name=$(echo "$file" | cut -d '-' -f 2-)
        echo "$name"
    fi
done
